using Junaid.GoogleGemini.Net.Infrastructure.Utilities;
using Junaid.GoogleGemini.Net.Models.Requests;
using Junaid.GoogleGemini.Net.Services.Interfaces;
using Xunit;

namespace Junaid.GoogleGemini.Net.IntegrationTests;

/// <summary>
/// Live tests for multimodal embeddings input (<c>gemini-embedding-2</c>). See
/// <c>PLAN-embeddings-multimodal.md</c> for the full research this feature was built from, including
/// every request/response shape live-verified before any code was written.
///
/// Test image/audio are generated by this library's own already-shipped image generation and TTS,
/// the same approach the plan's own research used. The PDF is a minimal hand-built one-page PDF
/// (no external dependency). Video input was not live-tested: this sandbox could not reach any
/// external source to fetch a small real video file (three different public sources all failed to
/// connect), and this library does not generate video. Confirmed via research (not via this suite)
/// against the same endpoint/mechanism as image and audio; see the plan's open items.
/// </summary>
[Collection("Live")]
public class MultimodalEmbeddingLiveTests(GeminiFixture fixture)
{
    private IGeminiService Gemini => fixture.Get<IGeminiService>();
    private IEmbeddingService Embeddings => fixture.Get<IEmbeddingService>();
    private IFileService Files => fixture.Get<IFileService>();

    [RequiresGeminiKey]
    public async Task EmbedContentAsync_Image_ReturnsRealNonDegenerateEmbedding()
    {
        var imageBytes = await GenerateImageAsync("A simple red circle on a white background.");

        var textOnly = await Embeddings.EmbedContentAsync(GeminiConstants.Models.GeminiEmbedding2, "A red circle");
        var withImage = await Embeddings.EmbedContentAsync(
            GeminiConstants.Models.GeminiEmbedding2, imageBytes, "image/jpeg", "A red circle");

        var a = textOnly.Embedding!.Values!;
        var b = withImage.Embedding!.Values!;

        Assert.NotEqual(a, b);

        // Cosine similarity should be meaningfully below 1.0 (the image changes the vector) and
        // meaningfully above 0 (still related content), mirroring the 0.528 confirmed in research.
        var cosine = CosineSimilarity(a, b);
        Assert.InRange(cosine, 0.1, 0.95);
    }

    [RequiresGeminiKey]
    public async Task EmbedContentAsync_AudioWithoutText_ReturnsValidEmbedding()
    {
        var audioBytes = await GenerateSpeechWavAsync("Say clearly: The stock market rallied today.");

        var response = await Embeddings.EmbedContentAsync(GeminiConstants.Models.GeminiEmbedding2, audioBytes, "audio/wav");

        Assert.NotNull(response.Embedding?.Values);
        Assert.True(response.Embedding!.Values!.Length >= 50);
    }

    [RequiresGeminiKey]
    public async Task EmbedFileAsync_AgainstAnUploadedImage_Succeeds()
    {
        var imageBytes = await GenerateImageAsync("A blue square.");
        var file = await Files.UploadFileAsync(imageBytes, "image/jpeg", "embed-live-test.jpg");

        var response = await Embeddings.EmbedFileAsync(GeminiConstants.Models.GeminiEmbedding2, file.Uri!, "image/jpeg", "A blue square");

        Assert.NotNull(response.Embedding?.Values);
    }

    [RequiresGeminiKey]
    public async Task EmbedContentAsync_Pdf_ReturnsValidEmbedding()
    {
        var pdfBytes = BuildMinimalPdf("Quarterly earnings report");

        var response = await Embeddings.EmbedContentAsync(
            GeminiConstants.Models.GeminiEmbedding2, pdfBytes, "application/pdf", "Earnings report");

        Assert.NotNull(response.Embedding?.Values);
        Assert.True(response.Embedding!.Values!.Length >= 50);
    }

    [RequiresGeminiKey]
    public async Task BatchEmbedContentAsync_MixedTextAndMultimodalInputs_ReturnsDistinctEmbeddingsInOrder()
    {
        var imageBytes = await GenerateImageAsync("A green triangle.");

        var response = await Embeddings.BatchEmbedContentAsync(
            GeminiConstants.Models.GeminiEmbedding2,
            new List<EmbeddingInput>
            {
                new() { Text = "a plain text entry about cats" },
                new() { Text = "A green triangle", MediaBytes = imageBytes, MimeType = "image/jpeg" },
            });

        Assert.Equal(2, response.Embeddings!.Length);
        Assert.NotEqual(response.Embeddings[0].Values, response.Embeddings[1].Values);
    }

    // PLAN-embeddings-multimodal.md §2: TaskType confirmed live (raw REST) to have zero effect on
    // gemini-embedding-2. This is the same confirmation through the actual typed client.
    [RequiresGeminiKey]
    public async Task EmbedContentAsync_TaskTypeOnGeminiEmbedding2_HasNoEffectOnTheOutput()
    {
        var withoutTaskType = await Embeddings.EmbedContentAsync(GeminiConstants.Models.GeminiEmbedding2, "Hello world");
        var withTaskType = await Embeddings.EmbedContentAsync(
            GeminiConstants.Models.GeminiEmbedding2, "Hello world",
            new EmbeddingOptions { TaskType = GeminiConstants.EmbeddingTaskTypes.RetrievalQuery });

        Assert.Equal(withoutTaskType.Embedding!.Values, withTaskType.Embedding!.Values);
    }

    private async Task<byte[]> GenerateImageAsync(string prompt)
    {
        var response = await Gemini.GenerateImageAsync(prompt);
        return response.GetImagesOrThrow()[0].Data;
    }

    private async Task<byte[]> GenerateSpeechWavAsync(string prompt)
    {
        var response = await Gemini.GenerateAudioAsync(prompt, new GeminiRequestOptions
        {
            Model = GeminiConstants.Models.Gemini25FlashTts,
            VoiceName = "Kore",
        });
        return response.GetAudioOrThrow().ToWav();
    }

    /// <summary>A minimal hand-built one-page PDF (no external dependency), for testing PDF input
    /// without a PDF-writing library in this test project.</summary>
    private static byte[] BuildMinimalPdf(string text)
    {
        var content = $"BT /F1 24 Tf 72 700 Td ({text}) Tj ET";
        var objs = new List<string>
        {
            "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
            "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
            "3 0 obj\n<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> /MediaBox [0 0 612 792] /Contents 5 0 R >>\nendobj\n",
            "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
            $"5 0 obj\n<< /Length {content.Length} >>\nstream\n{content}\nendstream\nendobj\n",
        };

        var pdf = "%PDF-1.4\n";
        var offsets = new List<int>();
        foreach (var o in objs)
        {
            offsets.Add(pdf.Length);
            pdf += o;
        }
        var xrefStart = pdf.Length;
        pdf += $"xref\n0 {objs.Count + 1}\n0000000000 65535 f \n";
        foreach (var off in offsets)
        {
            pdf += $"{off:D10} 00000 n \n";
        }
        pdf += $"trailer\n<< /Size {objs.Count + 1} /Root 1 0 R >>\nstartxref\n{xrefStart}\n%%EOF";

        return System.Text.Encoding.ASCII.GetBytes(pdf);
    }

    private static double CosineSimilarity(float[] a, float[] b)
    {
        double dot = 0, na = 0, nb = 0;
        for (var i = 0; i < a.Length; i++)
        {
            dot += a[i] * b[i];
            na += a[i] * a[i];
            nb += b[i] * b[i];
        }
        return dot / (Math.Sqrt(na) * Math.Sqrt(nb));
    }
}
