using System.Net;
using Junaid.GoogleGemini.Net.Exceptions;
using Junaid.GoogleGemini.Net.Infrastructure.Interfaces;
using Junaid.GoogleGemini.Net.Infrastructure.Utilities;
using Junaid.GoogleGemini.Net.Models.GoogleApi;
using Junaid.GoogleGemini.Net.Models.Requests;
using Junaid.GoogleGemini.Net.Services.Interfaces;
using Xunit;

namespace Junaid.GoogleGemini.Net.IntegrationTests;

/// <summary>
/// Live tests against the real Gemini speech-to-text model (<c>gemini-3.5-transcribe</c>, called
/// through the Interactions API). See <c>PLAN-stt.md</c> for the full research this feature was built
/// from, including every request/response shape live-verified before any code was written.
///
/// Test audio is generated by this library's own already-shipped TTS
/// (<see cref="IGeminiService.GenerateAudioAsync"/>), the same approach <c>PLAN-stt.md</c>'s own
/// research used: real speech with known content, not a synthetic tone.
/// </summary>
[Collection("Live")]
public class TranscriptionLiveTests(GeminiFixture fixture)
{
    private IGeminiService Gemini => fixture.Get<IGeminiService>();
    private ITranscriptionService Transcription => fixture.Get<ITranscriptionService>();
    private IFileService Files => fixture.Get<IFileService>();
    private IGeminiClient Client => fixture.Get<IGeminiClient>();

    [RequiresGeminiKey]
    public async Task TranscribeAsync_InlineAudio_ReturnsExpectedTranscript()
    {
        var wav = await GenerateSpeechWavAsync("Say clearly: The quick brown fox jumps over the lazy dog.");

        var interaction = await Transcription.TranscribeAsync(wav, "audio/wav");

        var text = interaction.GetTextOrThrow();
        Assert.Contains("quick brown fox", text, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("lazy dog", text, StringComparison.OrdinalIgnoreCase);
        Assert.Equal("completed", interaction.Status);
    }

    [RequiresGeminiKey]
    public async Task TranscribeAsync_WithDiarizationAndTimestamps_ReturnsDistinctSpeakerLabels()
    {
        var wav = await GenerateMultiSpeakerSpeechWavAsync(
            "TTS the following conversation between Joe and Jane: " +
            "Joe: Hey Jane, did you finish the report? Jane: Yes Joe, I sent it an hour ago.");

        var interaction = await Transcription.TranscribeAsync(wav, "audio/wav", new TranscriptionOptions
        {
            DiarizationMode = "speaker",
            TimestampGranularities = ["word"],
        });

        var words = interaction.Words();
        Assert.NotEmpty(words);

        var speakers = words.Select(w => w.Speaker).Where(s => s is not null).Distinct().ToList();
        Assert.True(speakers.Count >= 2, $"Expected at least 2 distinct speakers, got: {string.Join(", ", speakers)}");

        // Confirmed live shape (PLAN-stt.md §3.2): "spk:0"/"spk:1", not "spk_1".
        Assert.All(speakers, s => Assert.StartsWith("spk:", s));

        // Confirmed live shape: real audio-time offsets like "0.300s".
        Assert.All(words, w => Assert.NotNull(w.StartOffset));
        Assert.All(words, w => Assert.EndsWith("s", w.EndOffset));
    }

    [RequiresGeminiKey]
    public async Task TranscribeFileAsync_AgainstAnUploadedFile_Succeeds()
    {
        var wav = await GenerateSpeechWavAsync("Say clearly: Testing one two three.");
        var file = await Files.UploadFileAsync(wav, "audio/wav", "stt-live-test.wav");

        var interaction = await Transcription.TranscribeFileAsync(file.Uri!, "audio/wav");

        Assert.Contains("testing", interaction.GetTextOrThrow(), StringComparison.OrdinalIgnoreCase);
    }

    [RequiresGeminiKey]
    public async Task StreamTranscribeAsync_YieldsEventsAndAFinalCompletedInteractionWithUsage()
    {
        var wav = await GenerateSpeechWavAsync("Say clearly: Streaming transcription test.");

        var events = new List<InteractionStreamEvent>();
        await foreach (var evt in Transcription.StreamTranscribeAsync(wav, "audio/wav"))
        {
            events.Add(evt);
        }

        Assert.NotEmpty(events);

        var completed = events.LastOrDefault(e => e.Interaction?.Status == "completed");
        Assert.NotNull(completed?.Interaction);
        Assert.NotNull(completed!.Interaction!.Usage);

        var text = string.Concat(events.Where(e => e.DeltaText is not null).Select(e => e.DeltaText));
        Assert.Contains("streaming", text, StringComparison.OrdinalIgnoreCase);
    }

    // PLAN-stt.md §8: confirms the client-side guard in TranscriptionOptions.Validate() (unit-tested
    // in TranscriptionTests) actually matches the real API's rejection, by bypassing that guard and
    // calling IGeminiClient directly with the conflicting combination.
    [RequiresGeminiKey]
    public async Task PostInteractionAsync_CustomVocabularyWithDiarization_RealApiRejectsWithInvalidRequest()
    {
        var wav = await GenerateSpeechWavAsync("Say clearly: Vocabulary conflict test.");

        var request = new InteractionRequest
        {
            Model = GeminiConstants.Models.Gemini35Transcribe,
            Input = [new InteractionInput { Type = "audio", Data = Convert.ToBase64String(wav), MimeType = "audio/wav" }],
            GenerationConfig = new InteractionGenerationConfig
            {
                TranscriptionConfig = new TranscriptionConfig
                {
                    CustomVocabulary = ["Gemini"],
                    DiarizationMode = "speaker",
                },
            },
        };

        var ex = await Assert.ThrowsAsync<GeminiApiException>(() => Client.PostInteractionAsync(request));

        Assert.Equal(HttpStatusCode.BadRequest, ex.StatusCode);
        Assert.Equal("invalid_request", ex.InteractionErrorCode);
    }

    private async Task<byte[]> GenerateSpeechWavAsync(string prompt)
    {
        var response = await Gemini.GenerateAudioAsync(prompt, new GeminiRequestOptions
        {
            Model = GeminiConstants.Models.Gemini25FlashTts,
            VoiceName = "Kore",
        });
        return response.GetAudioOrThrow().ToWav();
    }

    private async Task<byte[]> GenerateMultiSpeakerSpeechWavAsync(string prompt)
    {
        var response = await Gemini.GenerateAudioAsync(prompt, new GeminiRequestOptions
        {
            Model = GeminiConstants.Models.Gemini25FlashTts,
            SpeakerVoices = [("Joe", "Kore"), ("Jane", "Puck")],
        });
        return response.GetAudioOrThrow().ToWav();
    }
}
