using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using Junaid.GoogleGemini.Net.Exceptions;

namespace Junaid.GoogleGemini.Net.Models.GoogleApi;

/// <summary>
/// The response returned by the Gemini <c>generateContent</c> endpoint.
/// </summary>
public class GenerateContentResponse
{
    /// <summary>Candidate responses generated by the model (usually one).</summary>
    [JsonPropertyName("candidates")]
    public Candidate[]? Candidates { get; set; }

    /// <summary>Feedback about the prompt, including any block reason and safety ratings.</summary>
    [JsonPropertyName("promptFeedback")]
    public PromptFeedback? PromptFeedback { get; set; }

    /// <summary>Token accounting for the request and response.</summary>
    [JsonPropertyName("usageMetadata")]
    public UsageMetadata? UsageMetadata { get; set; }

    /// <summary>Why generation finished for the first candidate (e.g. "STOP", "SAFETY"), if available.</summary>
    [JsonIgnore]
    public string? FinishReason => Candidates is { Length: > 0 } ? Candidates[0].FinishReason : null;

    /// <summary>Why the prompt was blocked, if applicable.</summary>
    [JsonIgnore]
    public string? BlockReason => PromptFeedback?.BlockReason;

    /// <summary>Token usage for this response, if reported.</summary>
    [JsonIgnore]
    public UsageMetadata? Usage => UsageMetadata;

    /// <summary>
    /// The concatenated text of the first candidate, or an <b>empty string</b> when the response
    /// carries no text (for example, when it was blocked). This never returns a placeholder
    /// sentence — use <see cref="TryGetText"/> or <see cref="GetTextOrThrow"/> to distinguish
    /// "no text" from a genuinely empty answer.
    /// </summary>
    public string Text() => GetTextInternal() ?? string.Empty;

    /// <summary>
    /// Gets the response text, returning <c>false</c> (and a null <paramref name="text"/>) when the
    /// response has no text content.
    /// </summary>
    public bool TryGetText([NotNullWhen(true)] out string? text)
    {
        text = GetTextInternal();
        return text is not null;
    }

    /// <summary>
    /// Gets the response text, or throws <see cref="GeminiContentException"/> (with the finish/block
    /// reason) when there is none. Use this when missing content should be treated as an error.
    /// </summary>
    public string GetTextOrThrow()
    {
        return GetTextInternal()
            ?? throw new GeminiContentException(
                "The response contained no text content.", FinishReason, BlockReason);
    }

    private string? GetTextInternal()
    {
        if (Candidates is not { Length: > 0 }) return null;
        if (Candidates[0].Content?.Parts is not { Count: > 0 } parts) return null;

        // A candidate can legitimately contain several text parts; join them.
        var joined = string.Concat(parts.Where(p => p.Text is not null).Select(p => p.Text));
        return string.IsNullOrEmpty(joined) ? null : joined;
    }
}

/// <summary>Feedback about the prompt that was sent to the model.</summary>
public class PromptFeedback
{
    /// <summary>Set when the prompt itself was blocked (e.g. "SAFETY"). Null when not blocked.</summary>
    [JsonPropertyName("blockReason")]
    public string? BlockReason { get; set; }

    /// <summary>Safety ratings computed for the prompt.</summary>
    [JsonPropertyName("safetyRatings")]
    public SafetyRating[]? SafetyRatings { get; set; }
}

/// <summary>A single candidate response from the model.</summary>
public class Candidate
{
    /// <summary>The generated content (role + parts).</summary>
    [JsonPropertyName("content")]
    public Content? Content { get; set; }

    /// <summary>Why generation stopped (e.g. "STOP", "MAX_TOKENS", "SAFETY").</summary>
    [JsonPropertyName("finishReason")]
    public string? FinishReason { get; set; }

    /// <summary>Zero-based index of this candidate.</summary>
    [JsonPropertyName("index")]
    public int Index { get; set; }

    /// <summary>Safety ratings for this candidate.</summary>
    [JsonPropertyName("safetyRatings")]
    public SafetyRating[]? SafetyRatings { get; set; }

    /// <summary>Grounding information (sources, queries) when a grounding tool was used.</summary>
    [JsonPropertyName("groundingMetadata")]
    public GroundingMetadata? GroundingMetadata { get; set; }
}

/// <summary>A safety rating for a single harm category.</summary>
public class SafetyRating
{
    /// <summary>The harm category (e.g. "HARM_CATEGORY_HATE_SPEECH").</summary>
    [JsonPropertyName("category")]
    public string? Category { get; set; }

    /// <summary>The assessed probability level (e.g. "NEGLIGIBLE", "LOW", "MEDIUM", "HIGH").</summary>
    [JsonPropertyName("probability")]
    public string? Probability { get; set; }
}

/// <summary>Token usage details for a generate-content request.</summary>
public class UsageMetadata
{
    /// <summary>Tokens consumed by the prompt.</summary>
    [JsonPropertyName("promptTokenCount")]
    public int PromptTokenCount { get; set; }

    /// <summary>Tokens produced across all candidates.</summary>
    [JsonPropertyName("candidatesTokenCount")]
    public int CandidatesTokenCount { get; set; }

    /// <summary>Total tokens billed for the request.</summary>
    [JsonPropertyName("totalTokenCount")]
    public int TotalTokenCount { get; set; }

    /// <summary>Tokens spent on internal "thinking" (billed as output), when thinking is enabled.</summary>
    [JsonPropertyName("thoughtsTokenCount")]
    public int ThoughtsTokenCount { get; set; }

    /// <summary>Tokens served from cached content, when context caching is used.</summary>
    [JsonPropertyName("cachedContentTokenCount")]
    public int CachedContentTokenCount { get; set; }
}
