using System.Text.Json.Serialization;

namespace Junaid.GoogleGemini.Net.Models.GoogleApi;

/// <summary>
/// The response returned by the Gemini <c>generateContent</c> endpoint.
/// </summary>
public class GenerateContentResponse
{
    /// <summary>Candidate responses generated by the model (usually one).</summary>
    [JsonPropertyName("candidates")]
    public Candidate[]? Candidates { get; set; }

    /// <summary>Feedback about the prompt, including any block reason and safety ratings.</summary>
    [JsonPropertyName("promptFeedback")]
    public PromptFeedback? PromptFeedback { get; set; }

    /// <summary>Token accounting for the request and response.</summary>
    [JsonPropertyName("usageMetadata")]
    public UsageMetadata? UsageMetadata { get; set; }

    /// <summary>
    /// Extracts the text of the first candidate, or returns a placeholder string when the response
    /// contains no usable content.
    /// </summary>
    /// <remarks>
    /// Phase 1 keeps this helper for source compatibility. Phase 2 replaces the placeholder strings
    /// with typed accessors (<c>TryGetText</c>, <c>FinishReason</c>) so callers can distinguish real
    /// output from a blocked/empty response.
    /// </remarks>
    public string Text()
    {
        var part = Candidates is { Length: > 0 }
            ? Candidates[0].Content?.Parts is { Count: > 0 } parts ? parts[0].Text : null
            : null;

        if (Candidates is null || Candidates.Length == 0)
        {
            return "[No content generated - response contained no candidates]";
        }

        if (Candidates[0].Content?.Parts is not { Count: > 0 })
        {
            return "[Content was blocked by safety filters]";
        }

        return string.IsNullOrEmpty(part) ? "[Content was blocked or empty]" : part!;
    }
}

/// <summary>Feedback about the prompt that was sent to the model.</summary>
public class PromptFeedback
{
    /// <summary>Set when the prompt itself was blocked (e.g. "SAFETY"). Null when not blocked.</summary>
    [JsonPropertyName("blockReason")]
    public string? BlockReason { get; set; }

    /// <summary>Safety ratings computed for the prompt.</summary>
    [JsonPropertyName("safetyRatings")]
    public SafetyRating[]? SafetyRatings { get; set; }
}

/// <summary>A single candidate response from the model.</summary>
public class Candidate
{
    /// <summary>The generated content (role + parts).</summary>
    [JsonPropertyName("content")]
    public Content? Content { get; set; }

    /// <summary>Why generation stopped (e.g. "STOP", "MAX_TOKENS", "SAFETY").</summary>
    [JsonPropertyName("finishReason")]
    public string? FinishReason { get; set; }

    /// <summary>Zero-based index of this candidate.</summary>
    [JsonPropertyName("index")]
    public int Index { get; set; }

    /// <summary>Safety ratings for this candidate.</summary>
    [JsonPropertyName("safetyRatings")]
    public SafetyRating[]? SafetyRatings { get; set; }
}

/// <summary>A safety rating for a single harm category.</summary>
public class SafetyRating
{
    /// <summary>The harm category (e.g. "HARM_CATEGORY_HATE_SPEECH").</summary>
    [JsonPropertyName("category")]
    public string? Category { get; set; }

    /// <summary>The assessed probability level (e.g. "NEGLIGIBLE", "LOW", "MEDIUM", "HIGH").</summary>
    [JsonPropertyName("probability")]
    public string? Probability { get; set; }
}

/// <summary>Token usage details for a generate-content request.</summary>
public class UsageMetadata
{
    /// <summary>Tokens consumed by the prompt.</summary>
    [JsonPropertyName("promptTokenCount")]
    public int PromptTokenCount { get; set; }

    /// <summary>Tokens produced across all candidates.</summary>
    [JsonPropertyName("candidatesTokenCount")]
    public int CandidatesTokenCount { get; set; }

    /// <summary>Total tokens billed for the request.</summary>
    [JsonPropertyName("totalTokenCount")]
    public int TotalTokenCount { get; set; }
}
