using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using Junaid.GoogleGemini.Net.Exceptions;

namespace Junaid.GoogleGemini.Net.Models.GoogleApi;

/// <summary>
/// The response returned by the Gemini <c>generateContent</c> endpoint.
/// </summary>
public class GenerateContentResponse
{
    /// <summary>Candidate responses generated by the model (usually one).</summary>
    [JsonPropertyName("candidates")]
    public Candidate[]? Candidates { get; set; }

    /// <summary>Feedback about the prompt, including any block reason and safety ratings.</summary>
    [JsonPropertyName("promptFeedback")]
    public PromptFeedback? PromptFeedback { get; set; }

    /// <summary>Token accounting for the request and response.</summary>
    [JsonPropertyName("usageMetadata")]
    public UsageMetadata? UsageMetadata { get; set; }

    /// <summary>Why generation finished for the first candidate (e.g. "STOP", "SAFETY"), if available.</summary>
    [JsonIgnore]
    public string? FinishReason => Candidates is { Length: > 0 } ? Candidates[0].FinishReason : null;

    /// <summary>Why the prompt was blocked, if applicable.</summary>
    [JsonIgnore]
    public string? BlockReason => PromptFeedback?.BlockReason;

    /// <summary>Token usage for this response, if reported.</summary>
    [JsonIgnore]
    public UsageMetadata? Usage => UsageMetadata;

    /// <summary>
    /// The concatenated text of the first candidate, or an <b>empty string</b> when the response
    /// carries no text (for example, when it was blocked). This never returns a placeholder
    /// sentence. Use <see cref="TryGetText"/> or <see cref="GetTextOrThrow"/> to distinguish
    /// "no text" from a genuinely empty answer.
    /// </summary>
    public string Text() => GetTextInternal() ?? string.Empty;

    /// <summary>
    /// Gets the response text, returning <c>false</c> (and a null <paramref name="text"/>) when the
    /// response has no text content.
    /// </summary>
    public bool TryGetText([NotNullWhen(true)] out string? text)
    {
        text = GetTextInternal();
        return text is not null;
    }

    /// <summary>
    /// Gets the response text, or throws <see cref="GeminiContentException"/> (with the finish/block
    /// reason) when there is none. Use this when missing content should be treated as an error.
    /// </summary>
    public string GetTextOrThrow()
    {
        return GetTextInternal()
            ?? throw new GeminiContentException(
                "The response contained no text content.", FinishReason, BlockReason);
    }

    private string? GetTextInternal()
    {
        if (Candidates is not { Length: > 0 }) return null;
        if (Candidates[0].Content?.Parts is not { Count: > 0 } parts) return null;

        // A candidate can legitimately contain several text parts; join them.
        var joined = string.Concat(parts.Where(p => p.Text is not null).Select(p => p.Text));
        return string.IsNullOrEmpty(joined) ? null : joined;
    }

    /// <summary>
    /// The generated images in the first candidate (from image-generation requests, see
    /// <c>IGeminiService.GenerateImageAsync</c>), or an empty list when there are none. Unlike
    /// <see cref="Text"/>, an empty list already unambiguously means "no images." No separate
    /// try/throw distinction is needed for "empty" vs "absent" the way a string requires.
    /// </summary>
    public IReadOnlyList<GeneratedImage> Images() => GetImagesInternal();

    /// <summary>
    /// Gets the generated images, returning <c>false</c> (and a null <paramref name="images"/>) when
    /// the response has none.
    /// </summary>
    public bool TryGetImages([NotNullWhen(true)] out IReadOnlyList<GeneratedImage>? images)
    {
        var found = GetImagesInternal();
        images = found.Count > 0 ? found : null;
        return images is not null;
    }

    /// <summary>
    /// Gets the generated images, or throws <see cref="GeminiContentException"/> (with the
    /// finish/block reason) when there are none. Use this when a missing image should be treated as
    /// an error.
    /// </summary>
    public IReadOnlyList<GeneratedImage> GetImagesOrThrow()
    {
        var found = GetImagesInternal();
        return found.Count > 0
            ? found
            : throw new GeminiContentException(
                "The response contained no generated images.", FinishReason, BlockReason);
    }

    private IReadOnlyList<GeneratedImage> GetImagesInternal()
    {
        if (Candidates is not { Length: > 0 }) return [];
        if (Candidates[0].Content?.Parts is not { Count: > 0 } parts) return [];

        // Deliberately filters to image/*. inlineData could in principle carry other binary kinds
        // in a future multimodal response (e.g. generated audio), which Images() should not surface.
        return parts
            .Select(p => p.InlineData)
            .Where(data => data is not null && data.MimeType.StartsWith("image/", StringComparison.OrdinalIgnoreCase))
            .Select(data => new GeneratedImage(data!.MimeType, Convert.FromBase64String(data.Data)))
            .ToList();
    }

    /// <summary>
    /// The generated audio in the first candidate (from TTS requests, see
    /// <c>IGeminiService.GenerateAudioAsync</c>), or null when there is none. Singular, unlike the
    /// plural <see cref="Images()"/>: nothing observed or documented suggests a TTS response ever
    /// returns more than one audio clip per call.
    /// </summary>
    public GeneratedAudio? Audio() => GetAudioInternal();

    /// <summary>
    /// Gets the generated audio, returning <c>false</c> (and a null <paramref name="audio"/>) when
    /// the response has none.
    /// </summary>
    public bool TryGetAudio([NotNullWhen(true)] out GeneratedAudio? audio)
    {
        audio = GetAudioInternal();
        return audio is not null;
    }

    /// <summary>
    /// Gets the generated audio, or throws <see cref="GeminiContentException"/> (with the
    /// finish/block reason) when there is none. Use this when missing audio should be treated as an
    /// error.
    /// </summary>
    public GeneratedAudio GetAudioOrThrow()
    {
        return GetAudioInternal()
            ?? throw new GeminiContentException(
                "The response contained no generated audio.", FinishReason, BlockReason);
    }

    private GeneratedAudio? GetAudioInternal()
    {
        if (Candidates is not { Length: > 0 }) return null;
        if (Candidates[0].Content?.Parts is not { Count: > 0 } parts) return null;

        var data = parts
            .Select(p => p.InlineData)
            .FirstOrDefault(d => d is not null && d.MimeType.StartsWith("audio/", StringComparison.OrdinalIgnoreCase));

        return data is null ? null : new GeneratedAudio(data.MimeType, Convert.FromBase64String(data.Data));
    }
}

/// <summary>A single generated image, decoded from a response <c>inlineData</c> part.</summary>
/// <param name="MimeType">The image's MIME type (e.g. <c>"image/png"</c>).</param>
/// <param name="Data">The raw, already-decoded image bytes.</param>
public sealed record GeneratedImage(string MimeType, byte[] Data);

/// <summary>A single generated audio clip, decoded from a response <c>inlineData</c> part.</summary>
/// <param name="MimeType">
/// The API's exact MIME type. Two real formats are live-confirmed (see <c>PLAN-tts.md</c> §2):
/// <c>"audio/L16;codec=pcm;rate=24000"</c> from 2.5-era TTS models, and
/// <c>"audio/l16; rate=24000; channels=1"</c> from <c>gemini-3.1-flash-tts-preview</c>. Either way
/// this is raw linear PCM, not a WAV or MP3 file.
/// </param>
/// <param name="Data">
/// The raw, already-decoded PCM audio bytes. NOT a playable file on its own; call
/// <see cref="ToWav"/> for that.
/// </param>
public sealed record GeneratedAudio(string MimeType, byte[] Data)
{
    /// <summary>
    /// Wraps <see cref="Data"/> in a minimal 44-byte WAV header, producing a file most players and
    /// browsers can open directly. Parses the sample rate (and channel count, when stated) from
    /// <see cref="MimeType"/>, since two real, live-confirmed formats exist: 2.5-era TTS models
    /// return <c>"audio/L16;codec=pcm;rate=24000"</c>, while <c>gemini-3.1-flash-tts-preview</c>
    /// returns <c>"audio/l16; rate=24000; channels=1"</c> instead (see <c>PLAN-tts.md</c> §2). Assumes
    /// mono when no channel count is stated, matching every model that predates the newer format.
    /// </summary>
    /// <exception cref="FormatException">
    /// <see cref="MimeType"/> does not start with <c>"audio/L16"</c> (case-insensitive) or has no
    /// parseable sample rate, for example a future model returning a different codec.
    /// </exception>
    public byte[] ToWav()
    {
        // Two real, live-confirmed mimeType shapes exist, not one (see PLAN-tts.md §2): the 2.5-era
        // TTS models return "audio/L16;codec=pcm;rate=24000" (capital L, no spaces, explicit codec),
        // while gemini-3.1-flash-tts-preview returns "audio/l16; rate=24000; channels=1" (lowercase,
        // spaced, no codec segment, an explicit channel count instead). A rigid single-format regex
        // built only from the first model tested threw FormatException on the second one actually
        // tried; this parses each piece independently so a third format variant with the same pieces
        // in a different order or spacing still works.
        if (!System.Text.RegularExpressions.Regex.IsMatch(MimeType, @"^audio/l16\b", System.Text.RegularExpressions.RegexOptions.IgnoreCase))
        {
            throw new FormatException(
                $"GeneratedAudio.ToWav() only understands \"audio/L16\" (16-bit linear PCM), but got \"{MimeType}\". " +
                "This model may return a different audio codec than every Gemini TTS model confirmed so far.");
        }

        var rateMatch = System.Text.RegularExpressions.Regex.Match(MimeType, @"rate=(\d+)", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
        if (!rateMatch.Success)
        {
            throw new FormatException(
                $"GeneratedAudio.ToWav() could not find a \"rate=NNNN\" sample rate in \"{MimeType}\".");
        }

        var sampleRate = int.Parse(rateMatch.Groups[1].Value);

        // Defaults to 1 (mono) when the mimeType doesn't say, matching every Gemini TTS model
        // confirmed before gemini-3.1-flash-tts-preview started stating it explicitly.
        var channelsMatch = System.Text.RegularExpressions.Regex.Match(MimeType, @"channels=(\d+)", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
        var channels = channelsMatch.Success ? int.Parse(channelsMatch.Groups[1].Value) : 1;
        const int bitsPerSample = 16;
        var byteRate = sampleRate * channels * bitsPerSample / 8;
        var blockAlign = (short)(channels * bitsPerSample / 8);

        // Plain byte[]/BinaryWriter.Write(byte[]) throughout, not "..."u8 + Write(ReadOnlySpan<byte>):
        // that overload isn't in netstandard2.0's BCL, which this library still targets.
        using var stream = new MemoryStream(44 + Data.Length);
        using (var writer = new BinaryWriter(stream))
        {
            writer.Write(System.Text.Encoding.ASCII.GetBytes("RIFF"));
            writer.Write(36 + Data.Length);
            writer.Write(System.Text.Encoding.ASCII.GetBytes("WAVE"));
            writer.Write(System.Text.Encoding.ASCII.GetBytes("fmt "));
            writer.Write(16); // Subchunk1Size for PCM
            writer.Write((short)1); // AudioFormat: 1 = PCM
            writer.Write((short)channels);
            writer.Write(sampleRate);
            writer.Write(byteRate);
            writer.Write(blockAlign);
            writer.Write((short)bitsPerSample);
            writer.Write(System.Text.Encoding.ASCII.GetBytes("data"));
            writer.Write(Data.Length);
            writer.Write(Data);
        }

        return stream.ToArray();
    }
}

/// <summary>Feedback about the prompt that was sent to the model.</summary>
public class PromptFeedback
{
    /// <summary>Set when the prompt itself was blocked (e.g. "SAFETY"). Null when not blocked.</summary>
    [JsonPropertyName("blockReason")]
    public string? BlockReason { get; set; }

    /// <summary>Safety ratings computed for the prompt.</summary>
    [JsonPropertyName("safetyRatings")]
    public SafetyRating[]? SafetyRatings { get; set; }
}

/// <summary>A single candidate response from the model.</summary>
public class Candidate
{
    /// <summary>The generated content (role + parts).</summary>
    [JsonPropertyName("content")]
    public Content? Content { get; set; }

    /// <summary>Why generation stopped (e.g. "STOP", "MAX_TOKENS", "SAFETY").</summary>
    [JsonPropertyName("finishReason")]
    public string? FinishReason { get; set; }

    /// <summary>Zero-based index of this candidate.</summary>
    [JsonPropertyName("index")]
    public int Index { get; set; }

    /// <summary>Safety ratings for this candidate.</summary>
    [JsonPropertyName("safetyRatings")]
    public SafetyRating[]? SafetyRatings { get; set; }

    /// <summary>Grounding information (sources, queries) when a grounding tool was used.</summary>
    [JsonPropertyName("groundingMetadata")]
    public GroundingMetadata? GroundingMetadata { get; set; }

    /// <summary>
    /// Per-URL retrieval status when the <c>url_context</c> tool was used (e.g.
    /// <see cref="Requests.GeminiRequestOptions.EnableUrlContext"/>). The retrieved page content
    /// itself isn't echoed back here -- only whether each URL was fetched successfully.
    /// </summary>
    [JsonPropertyName("urlContextMetadata")]
    public UrlContextMetadata? UrlContextMetadata { get; set; }
}

/// <summary>Retrieval status for the URLs the <c>url_context</c> tool fetched.</summary>
public class UrlContextMetadata
{
    /// <summary>One entry per URL the model attempted to retrieve.</summary>
    [JsonPropertyName("urlMetadata")]
    public UrlMetadata[]? UrlMetadata { get; set; }
}

/// <summary>Retrieval status for a single URL fetched by the <c>url_context</c> tool.</summary>
public class UrlMetadata
{
    /// <summary>The URL that was retrieved.</summary>
    [JsonPropertyName("retrievedUrl")]
    public string? RetrievedUrl { get; set; }

    /// <summary>The outcome of the fetch (e.g. <c>"URL_RETRIEVAL_STATUS_SUCCESS"</c>).</summary>
    [JsonPropertyName("urlRetrievalStatus")]
    public string? UrlRetrievalStatus { get; set; }
}

/// <summary>A safety rating for a single harm category.</summary>
public class SafetyRating
{
    /// <summary>The harm category (e.g. "HARM_CATEGORY_HATE_SPEECH").</summary>
    [JsonPropertyName("category")]
    public string? Category { get; set; }

    /// <summary>The assessed probability level (e.g. "NEGLIGIBLE", "LOW", "MEDIUM", "HIGH").</summary>
    [JsonPropertyName("probability")]
    public string? Probability { get; set; }
}

/// <summary>Token usage details for a generate-content request.</summary>
public class UsageMetadata
{
    /// <summary>Tokens consumed by the prompt.</summary>
    [JsonPropertyName("promptTokenCount")]
    public int PromptTokenCount { get; set; }

    /// <summary>Tokens produced across all candidates.</summary>
    [JsonPropertyName("candidatesTokenCount")]
    public int CandidatesTokenCount { get; set; }

    /// <summary>Total tokens billed for the request.</summary>
    [JsonPropertyName("totalTokenCount")]
    public int TotalTokenCount { get; set; }

    /// <summary>Tokens spent on internal "thinking" (billed as output), when thinking is enabled.</summary>
    [JsonPropertyName("thoughtsTokenCount")]
    public int ThoughtsTokenCount { get; set; }

    /// <summary>Tokens served from cached content, when context caching is used.</summary>
    [JsonPropertyName("cachedContentTokenCount")]
    public int CachedContentTokenCount { get; set; }

    /// <summary>
    /// Per-modality breakdown of <see cref="PromptTokenCount"/> (e.g. how many prompt tokens were
    /// TEXT vs IMAGE). Live-confirmed present on the real API (2026-08-15, a native image-generation
    /// response) but not documented ahead of time in any of the sources this library was built from,
    /// so it went uncaptured until now. Null when the API omits it (observed on plain-text responses).
    /// </summary>
    [JsonPropertyName("promptTokensDetails")]
    public List<ModalityTokenCount>? PromptTokensDetails { get; set; }

    /// <summary>
    /// Per-modality breakdown of <see cref="CandidatesTokenCount"/> (e.g. how many output tokens were
    /// TEXT vs IMAGE on a native image-generation response). See <see cref="PromptTokensDetails"/> for
    /// how this was found. This is what would let a future cost-governance pricing pass distinguish
    /// text/thinking output tokens from image output tokens on mixed-modality models like
    /// gemini-3-pro-image, instead of pricing the whole response at the image rate.
    /// </summary>
    [JsonPropertyName("candidatesTokensDetails")]
    public List<ModalityTokenCount>? CandidatesTokensDetails { get; set; }
}

/// <summary>One entry in a <see cref="UsageMetadata"/> per-modality token breakdown.</summary>
public class ModalityTokenCount
{
    /// <summary>The content modality, e.g. <c>"TEXT"</c>, <c>"IMAGE"</c>, <c>"AUDIO"</c>.</summary>
    [JsonPropertyName("modality")]
    public string? Modality { get; set; }

    /// <summary>Token count for this modality.</summary>
    [JsonPropertyName("tokenCount")]
    public int TokenCount { get; set; }
}
